INFO 2023-02-17 18:50:24,793 autoreload 13212 7348 Watching for file changes with StatReloader
INFO 2023-02-17 18:51:03,239 autoreload 13212 7348 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\accounts\api.py changed, reloading.
INFO 2023-02-17 18:51:04,723 autoreload 12856 16056 Watching for file changes with StatReloader
INFO 2023-02-20 15:48:38,363 autoreload 9044 11652 Watching for file changes with StatReloader
INFO 2023-02-27 16:42:36,723 autoreload 10564 21264 Watching for file changes with StatReloader
INFO 2023-02-27 16:43:36,387 autoreload 15756 21020 Watching for file changes with StatReloader
WARNING 2023-02-27 16:43:40,520 log 15756 13464 Not Found: /
WARNING 2023-02-27 16:43:40,521 basehttp 15756 13464 "GET / HTTP/1.1" 404 3101
WARNING 2023-02-27 16:43:40,660 log 15756 13464 Not Found: /favicon.ico
WARNING 2023-02-27 16:43:40,660 basehttp 15756 13464 "GET /favicon.ico HTTP/1.1" 404 3152
INFO 2023-02-27 16:43:47,286 basehttp 15756 13464 "GET /admin/ HTTP/1.1" 200 8053
INFO 2023-02-27 16:43:47,378 basehttp 15756 13464 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,379 basehttp 15756 12432 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,380 basehttp 15756 7940 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,381 basehttp 15756 7632 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,420 basehttp 15756 12432 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,420 basehttp 15756 13464 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,477 basehttp 15756 12432 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,496 basehttp 15756 12432 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,497 basehttp 15756 13464 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,543 basehttp 15756 7940 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,646 basehttp 15756 7940 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,647 basehttp 15756 13464 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-02-27 16:43:47,651 basehttp 15756 12432 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,493 basehttp 15756 12432 "GET /admin/home/accepted/ HTTP/1.1" 200 12185
INFO 2023-02-27 16:43:49,579 basehttp 15756 12432 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,580 basehttp 15756 7940 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,582 basehttp 15756 15332 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,582 basehttp 15756 13464 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,587 basehttp 15756 12432 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,588 basehttp 15756 7940 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,589 basehttp 15756 13968 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,594 basehttp 15756 13464 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,594 basehttp 15756 15332 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,771 basehttp 15756 13968 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2023-02-27 16:43:49,901 basehttp 15756 7632 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 16:43:49,949 basehttp 15756 7632 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2023-02-27 16:43:54,197 basehttp 15756 7632 "GET /admin/ HTTP/1.1" 200 8053
INFO 2023-02-27 16:46:49,779 autoreload 13968 7632 Watching for file changes with StatReloader
WARNING 2023-02-27 16:46:51,153 log 13968 16500 Not Found: /
WARNING 2023-02-27 16:46:51,154 basehttp 13968 16500 "GET / HTTP/1.1" 404 3101
INFO 2023-02-27 16:46:58,210 basehttp 13968 16500 "GET /admin/ HTTP/1.1" 200 8053
INFO 2023-02-27 16:47:00,765 basehttp 13968 16500 "GET /admin/home/accepted/ HTTP/1.1" 200 12185
INFO 2023-02-27 16:47:01,256 basehttp 13968 16500 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 17:02:09,632 autoreload 20120 10856 Watching for file changes with StatReloader
INFO 2023-02-27 17:10:34,647 autoreload 16924 1892 Watching for file changes with StatReloader
WARNING 2023-02-27 17:10:36,864 log 16924 5024 Not Found: /
WARNING 2023-02-27 17:10:36,865 basehttp 16924 5024 "GET / HTTP/1.1" 404 3101
WARNING 2023-02-27 17:10:37,131 log 16924 5024 Not Found: /favicon.ico
WARNING 2023-02-27 17:10:37,131 basehttp 16924 5024 "GET /favicon.ico HTTP/1.1" 404 3152
INFO 2023-02-27 17:10:43,496 basehttp 16924 5024 "GET /admin/ HTTP/1.1" 200 8053
INFO 2023-02-27 17:10:45,402 basehttp 16924 5024 "GET /admin/home/accepted/ HTTP/1.1" 200 12506
INFO 2023-02-27 17:10:45,490 basehttp 16924 13452 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2023-02-27 17:10:45,914 basehttp 16924 5024 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 17:10:51,136 basehttp 16924 5024 "GET /admin/home/accepted/?q=rat HTTP/1.1" 200 8891
INFO 2023-02-27 17:10:51,500 basehttp 16924 5024 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 17:10:57,469 basehttp 16924 5024 "GET /admin/home/accepted/?q=greet HTTP/1.1" 200 8909
INFO 2023-02-27 17:10:57,949 basehttp 16924 5024 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 17:11:00,364 basehttp 16924 5024 "GET /admin/home/accepted/?q=rat HTTP/1.1" 200 8891
INFO 2023-02-27 17:11:04,991 basehttp 16924 5024 "GET /admin/home/accepted/ HTTP/1.1" 200 12506
INFO 2023-02-27 17:45:49,321 autoreload 16268 20696 Watching for file changes with StatReloader
INFO 2023-02-27 17:45:52,350 basehttp 16268 17420 "POST /api/add-after-search HTTP/1.1" 200 17
INFO 2023-02-27 17:46:00,247 basehttp 16268 17420 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-02-27 17:46:06,247 basehttp 16268 20212 "GET /admin/home/accepted/ HTTP/1.1" 200 12506
INFO 2023-02-27 17:46:06,691 basehttp 16268 20212 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-02-27 17:46:07,020 log 16268 20212 Not Found: /favicon.ico
WARNING 2023-02-27 17:46:07,020 basehttp 16268 20212 "GET /favicon.ico HTTP/1.1" 404 3344
INFO 2023-02-27 17:46:09,710 basehttp 16268 20212 "GET /admin/home/rhymes/ HTTP/1.1" 200 8943
INFO 2023-02-27 17:46:10,196 basehttp 16268 20212 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 17:51:22,140 autoreload 16432 5876 Watching for file changes with StatReloader
WARNING 2023-02-27 17:51:23,389 log 16432 6332 Not Found: /
WARNING 2023-02-27 17:51:23,389 basehttp 16432 6332 "GET / HTTP/1.1" 404 3293
WARNING 2023-02-27 17:51:23,535 log 16432 6332 Not Found: /favicon.ico
WARNING 2023-02-27 17:51:23,536 basehttp 16432 6332 "GET /favicon.ico HTTP/1.1" 404 3344
WARNING 2023-02-27 17:51:34,440 log 16432 6332 Method Not Allowed: /api/add-after-search
WARNING 2023-02-27 17:51:34,441 basehttp 16432 6332 "GET /api/add-after-search HTTP/1.1" 405 5668
INFO 2023-02-27 17:51:34,648 basehttp 16432 12268 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2023-02-27 17:51:34,654 basehttp 16432 7556 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2023-02-27 17:51:34,656 basehttp 16432 12268 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2023-02-27 17:51:34,669 basehttp 16432 12268 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2023-02-27 17:51:34,670 basehttp 16432 7556 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
INFO 2023-02-27 17:51:34,670 basehttp 16432 6332 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2023-02-27 17:51:34,692 basehttp 16432 6332 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2023-02-27 17:51:34,707 basehttp 16432 12268 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2023-02-27 17:51:34,725 basehttp 16432 6332 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2023-02-27 17:51:34,726 basehttp 16432 7556 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2023-02-27 17:51:34,741 basehttp 16432 7556 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2023-02-27 17:57:25,000 basehttp 16432 15524 "GET /admin/home/rhymes/ HTTP/1.1" 200 8943
INFO 2023-02-27 17:57:25,453 basehttp 16432 15524 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-02-27 17:57:25,539 log 16432 15524 Not Found: /favicon.ico
WARNING 2023-02-27 17:57:25,540 basehttp 16432 15524 "GET /favicon.ico HTTP/1.1" 404 3344
INFO 2023-02-27 17:57:27,444 basehttp 16432 15524 "GET /admin/home/rhymes/ HTTP/1.1" 200 8943
INFO 2023-02-27 17:57:27,941 basehttp 16432 15524 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 18:27:59,477 basehttp 16432 416 "POST /api/add-after-search HTTP/1.1" 200 5618
INFO 2023-02-27 18:28:31,392 basehttp 16432 416 "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 200 540434
INFO 2023-02-27 20:09:03,619 basehttp 16432 13612 "GET /admin/home/rhymes/ HTTP/1.1" 200 9256
INFO 2023-02-27 20:09:04,106 basehttp 16432 13612 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-02-27 20:32:24,292 basehttp 16432 15048 "GET /admin/home/rhymes/ HTTP/1.1" 200 9256
INFO 2023-02-27 20:32:24,773 basehttp 16432 15048 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-02 17:23:04,903 autoreload 6424 20296 Watching for file changes with StatReloader
WARNING 2023-03-02 17:23:51,120 log 6424 7308 Not Found: /api/search-rhyming-words
WARNING 2023-03-02 17:23:51,121 basehttp 6424 7308 "GET /api/search-rhyming-words HTTP/1.1" 404 3959
INFO 2023-03-02 17:24:07,869 autoreload 6424 20296 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:24:09,488 autoreload 16100 9392 Watching for file changes with StatReloader
INFO 2023-03-02 17:24:18,295 autoreload 16100 9392 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\urls.py changed, reloading.
INFO 2023-03-02 17:24:19,776 autoreload 384 17928 Watching for file changes with StatReloader
ERROR 2023-03-02 17:24:21,167 log 384 20980 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print(list(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:24:21,169 basehttp 384 20980 "GET /api/search-rhyming-words HTTP/1.1" 500 94988
ERROR 2023-03-02 17:24:23,220 log 384 20980 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print(list(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:24:23,221 basehttp 384 20980 "GET /api/search-rhyming-words HTTP/1.1" 500 94988
INFO 2023-03-02 17:24:50,970 autoreload 384 17928 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:24:52,509 autoreload 11064 16576 Watching for file changes with StatReloader
ERROR 2023-03-02 17:25:03,065 log 11064 19932 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print(list(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:25:03,067 basehttp 11064 19932 "GET /api/search-rhyming-words HTTP/1.1" 500 94992
INFO 2023-03-02 17:25:12,347 autoreload 11064 16576 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:25:13,497 autoreload 21444 14276 Watching for file changes with StatReloader
INFO 2023-03-02 17:26:20,418 autoreload 21444 14276 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:26:21,876 autoreload 12592 9876 Watching for file changes with StatReloader
INFO 2023-03-02 17:26:24,496 basehttp 12592 20192 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:26:38,352 autoreload 12592 9876 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:26:39,602 autoreload 11568 9320 Watching for file changes with StatReloader
INFO 2023-03-02 17:26:47,403 basehttp 11568 20424 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:26:48,580 basehttp 11568 20424 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:27:48,103 autoreload 11568 9320 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:27:49,506 autoreload 14800 12724 Watching for file changes with StatReloader
INFO 2023-03-02 17:28:55,807 autoreload 14800 12724 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:28:57,343 autoreload 624 7660 Watching for file changes with StatReloader
ERROR 2023-03-02 17:29:00,199 log 624 2444 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",list(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:29:00,201 basehttp 624 2444 "GET /api/search-rhyming-words HTTP/1.1" 500 95046
INFO 2023-03-02 17:29:16,427 autoreload 624 7660 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:29:18,077 autoreload 9036 18224 Watching for file changes with StatReloader
ERROR 2023-03-02 17:29:21,449 log 9036 17212 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",dict(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:29:21,450 basehttp 9036 17212 "GET /api/search-rhyming-words HTTP/1.1" 500 95046
INFO 2023-03-02 17:32:45,392 autoreload 9036 18224 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:32:47,298 autoreload 3724 7356 Watching for file changes with StatReloader
ERROR 2023-03-02 17:32:49,891 log 3724 16860 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",i.values)
AttributeError: 'Accepted' object has no attribute 'values'
ERROR 2023-03-02 17:32:49,893 basehttp 3724 16860 "GET /api/search-rhyming-words HTTP/1.1" 500 95208
INFO 2023-03-02 17:33:02,352 autoreload 3724 7356 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:33:03,865 autoreload 6832 12272 Watching for file changes with StatReloader
INFO 2023-03-02 17:33:10,500 basehttp 6832 15568 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:33:28,191 autoreload 6832 12272 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:33:29,462 autoreload 16964 6956 Watching for file changes with StatReloader
INFO 2023-03-02 17:33:31,792 basehttp 16964 11040 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:33:43,455 autoreload 16964 6956 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:33:44,934 autoreload 2368 6772 Watching for file changes with StatReloader
ERROR 2023-03-02 17:33:45,941 log 2368 17060 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",i.data)
AttributeError: 'Accepted' object has no attribute 'data'
ERROR 2023-03-02 17:33:45,943 basehttp 2368 17060 "GET /api/search-rhyming-words HTTP/1.1" 500 95192
INFO 2023-03-02 17:33:53,919 autoreload 2368 6772 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:33:55,412 autoreload 17036 1320 Watching for file changes with StatReloader
INFO 2023-03-02 17:35:21,306 autoreload 17036 1320 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:35:22,816 autoreload 19460 20556 Watching for file changes with StatReloader
ERROR 2023-03-02 17:35:24,100 log 19460 17100 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",i.values())
AttributeError: 'Accepted' object has no attribute 'values'
ERROR 2023-03-02 17:35:24,103 basehttp 19460 17100 "GET /api/search-rhyming-words HTTP/1.1" 500 95212
INFO 2023-03-02 17:35:39,902 autoreload 19460 20556 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:35:41,289 autoreload 18512 20620 Watching for file changes with StatReloader
ERROR 2023-03-02 17:35:43,117 log 18512 21168 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching",list(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:35:43,119 basehttp 18512 21168 "GET /api/search-rhyming-words HTTP/1.1" 500 95046
INFO 2023-03-02 17:37:07,881 autoreload 18512 20620 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:37:08,958 autoreload 18204 11604 Watching for file changes with StatReloader
ERROR 2023-03-02 17:37:11,403 log 18204 13892 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 172, in get
    for i in range(user_info):
TypeError: 'QuerySet' object cannot be interpreted as an integer
ERROR 2023-03-02 17:37:11,406 basehttp 18204 13892 "GET /api/search-rhyming-words HTTP/1.1" 500 94304
ERROR 2023-03-02 17:37:12,509 log 18204 13892 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 172, in get
    for i in range(user_info):
TypeError: 'QuerySet' object cannot be interpreted as an integer
ERROR 2023-03-02 17:37:12,511 basehttp 18204 13892 "GET /api/search-rhyming-words HTTP/1.1" 500 94304
INFO 2023-03-02 17:37:20,950 autoreload 18204 11604 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:37:22,790 autoreload 1468 11828 Watching for file changes with StatReloader
ERROR 2023-03-02 17:37:23,153 log 1468 16400 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 172, in get
    for i in range(user_info):
TypeError: 'QuerySet' object cannot be interpreted as an integer
ERROR 2023-03-02 17:37:23,155 basehttp 1468 16400 "GET /api/search-rhyming-words HTTP/1.1" 500 94300
ERROR 2023-03-02 17:37:24,318 log 1468 16400 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 172, in get
    for i in range(user_info):
TypeError: 'QuerySet' object cannot be interpreted as an integer
ERROR 2023-03-02 17:37:24,319 basehttp 1468 16400 "GET /api/search-rhyming-words HTTP/1.1" 500 94300
ERROR 2023-03-02 17:37:24,864 log 1468 16400 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 172, in get
    for i in range(user_info):
TypeError: 'QuerySet' object cannot be interpreted as an integer
ERROR 2023-03-02 17:37:24,866 basehttp 1468 16400 "GET /api/search-rhyming-words HTTP/1.1" 500 94300
INFO 2023-03-02 17:38:59,031 autoreload 1468 11828 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:39:00,476 autoreload 18264 13572 Watching for file changes with StatReloader
INFO 2023-03-02 17:39:09,062 autoreload 18264 13572 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:39:10,234 autoreload 15876 15808 Watching for file changes with StatReloader
INFO 2023-03-02 17:39:38,718 autoreload 15876 15808 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:39:40,123 autoreload 17160 7412 Watching for file changes with StatReloader
ERROR 2023-03-02 17:39:44,239 log 17160 9336 Internal Server Error: /api/search-rhyming-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 174, in get
    print("Inside searching", dict(i))
TypeError: 'Accepted' object is not iterable
ERROR 2023-03-02 17:39:44,241 basehttp 17160 9336 "GET /api/search-rhyming-words HTTP/1.1" 500 95048
INFO 2023-03-02 17:39:52,063 autoreload 17160 7412 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:39:53,504 autoreload 15764 1900 Watching for file changes with StatReloader
INFO 2023-03-02 17:39:54,864 basehttp 15764 16424 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:42:53,776 autoreload 15764 1900 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:42:55,192 autoreload 9060 19532 Watching for file changes with StatReloader
INFO 2023-03-02 17:43:01,060 basehttp 9060 8740 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 17:45:06,356 autoreload 9060 19532 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 17:45:08,085 autoreload 12048 14412 Watching for file changes with StatReloader
INFO 2023-03-02 17:45:13,132 basehttp 12048 8448 "GET /api/search-rhyming-words HTTP/1.1" 200 1320
INFO 2023-03-02 18:25:15,734 autoreload 12048 14412 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 18:25:17,482 autoreload 12032 1508 Watching for file changes with StatReloader
INFO 2023-03-02 20:00:31,121 autoreload 12032 1508 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\models.py changed, reloading.
INFO 2023-03-02 20:00:33,452 autoreload 6072 15764 Watching for file changes with StatReloader
INFO 2023-03-02 20:22:34,737 autoreload 6072 15764 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\models.py changed, reloading.
INFO 2023-03-02 20:22:36,057 autoreload 16308 11180 Watching for file changes with StatReloader
INFO 2023-03-02 20:22:54,660 autoreload 16308 11180 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\models.py changed, reloading.
INFO 2023-03-02 20:22:56,179 autoreload 19336 15228 Watching for file changes with StatReloader
INFO 2023-03-02 20:24:30,516 autoreload 19336 15228 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\admin.py changed, reloading.
INFO 2023-03-02 20:24:32,055 autoreload 7512 14352 Watching for file changes with StatReloader
INFO 2023-03-02 20:24:53,440 autoreload 7512 14352 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\admin.py changed, reloading.
INFO 2023-03-02 20:24:54,664 autoreload 9868 15520 Watching for file changes with StatReloader
INFO 2023-03-02 20:25:19,211 autoreload 9868 15520 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-02 20:25:20,393 autoreload 3612 20300 Watching for file changes with StatReloader
INFO 2023-03-02 20:31:47,079 autoreload 17632 2668 Watching for file changes with StatReloader
INFO 2023-03-02 20:32:29,638 autoreload 1348 19572 Watching for file changes with StatReloader
WARNING 2023-03-02 20:32:32,296 log 1348 10752 Not Found: /
WARNING 2023-03-02 20:32:32,297 basehttp 1348 10752 "GET / HTTP/1.1" 404 3293
WARNING 2023-03-02 20:32:32,464 log 1348 10752 Not Found: /favicon.ico
WARNING 2023-03-02 20:32:32,465 basehttp 1348 10752 "GET /favicon.ico HTTP/1.1" 404 3344
INFO 2023-03-02 20:32:37,923 basehttp 1348 10752 "GET /admin/ HTTP/1.1" 200 8493
INFO 2023-03-02 20:32:37,971 basehttp 1348 10752 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:37,971 basehttp 1348 8644 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:37,978 basehttp 1348 8644 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:37,978 basehttp 1348 10752 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:37,985 basehttp 1348 21304 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,085 basehttp 1348 21304 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,085 basehttp 1348 8644 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,107 basehttp 1348 21304 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,107 basehttp 1348 8644 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,113 basehttp 1348 21304 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,291 basehttp 1348 8644 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,291 basehttp 1348 21304 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-02 20:32:38,292 basehttp 1348 10752 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-03 20:19:37,706 autoreload 7712 10988 Watching for file changes with StatReloader
WARNING 2023-03-03 20:21:05,644 log 7712 6776 Method Not Allowed: /api/add-random-words
WARNING 2023-03-03 20:21:05,644 basehttp 7712 6776 "GET /api/add-random-words HTTP/1.1" 405 40
INFO 2023-03-03 20:21:10,741 basehttp 7712 6776 "POST /api/add-random-words HTTP/1.1" 200 17
WARNING 2023-03-03 20:22:23,113 log 7712 6636 Not Found: /
WARNING 2023-03-03 20:22:23,115 basehttp 7712 6636 "GET / HTTP/1.1" 404 3485
WARNING 2023-03-03 20:22:23,355 log 7712 6636 Not Found: /favicon.ico
WARNING 2023-03-03 20:22:23,356 basehttp 7712 6636 "GET /favicon.ico HTTP/1.1" 404 3536
INFO 2023-03-03 20:22:42,397 basehttp 7712 6636 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-03-03 20:22:42,781 basehttp 7712 6636 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
INFO 2023-03-03 20:22:42,920 basehttp 7712 6636 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2023-03-03 20:22:46,298 basehttp 7712 6636 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-03-03 20:22:46,710 basehttp 7712 6636 "GET /admin/ HTTP/1.1" 200 8493
INFO 2023-03-03 20:22:53,522 basehttp 7712 6636 "GET /admin/home/randomwords/ HTTP/1.1" 200 6612
INFO 2023-03-03 20:22:53,567 basehttp 7712 6636 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,573 basehttp 7712 6636 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,584 basehttp 7712 6636 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,585 basehttp 7712 16784 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,587 basehttp 7712 18976 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,588 basehttp 7712 4836 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,594 basehttp 7712 16784 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,600 basehttp 7712 18976 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,605 basehttp 7712 19228 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,719 basehttp 7712 6636 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2023-03-03 20:22:53,966 basehttp 7712 16564 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-03 20:22:54,014 basehttp 7712 16564 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2023-03-03 20:24:45,167 autoreload 7712 10988 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:24:46,251 autoreload 14112 14416 Watching for file changes with StatReloader
INFO 2023-03-03 20:24:51,491 basehttp 14112 5540 "POST /api/add-random-words HTTP/1.1" 200 17
INFO 2023-03-03 20:24:52,324 basehttp 14112 5540 "POST /api/add-random-words HTTP/1.1" 200 17
INFO 2023-03-03 20:25:15,743 autoreload 14112 14416 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:25:17,044 autoreload 18208 2940 Watching for file changes with StatReloader
INFO 2023-03-03 20:25:28,013 autoreload 18208 2940 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:25:29,328 autoreload 3560 8960 Watching for file changes with StatReloader
INFO 2023-03-03 20:25:41,401 basehttp 3560 6416 "POST /api/add-random-words HTTP/1.1" 200 17
INFO 2023-03-03 20:26:30,995 autoreload 3560 8960 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:26:32,383 autoreload 14640 8180 Watching for file changes with StatReloader
INFO 2023-03-03 20:31:04,551 autoreload 14640 8180 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:31:05,972 autoreload 20280 18056 Watching for file changes with StatReloader
INFO 2023-03-03 20:31:09,519 basehttp 20280 12960 "POST /api/add-random-words HTTP/1.1" 200 17
INFO 2023-03-03 20:34:53,864 autoreload 20280 18056 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:34:55,531 autoreload 9736 13100 Watching for file changes with StatReloader
ERROR 2023-03-03 20:34:56,074 log 9736 20436 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:34:56,077 basehttp 9736 20436 "POST /api/add-random-words HTTP/1.1" 500 99203
INFO 2023-03-03 20:35:40,076 autoreload 9736 13100 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:35:41,508 autoreload 17168 13180 Watching for file changes with StatReloader
ERROR 2023-03-03 20:35:45,703 log 17168 13768 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:35:45,707 basehttp 17168 13768 "POST /api/add-random-words HTTP/1.1" 500 99199
ERROR 2023-03-03 20:35:55,762 log 17168 13768 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:35:55,764 basehttp 17168 13768 "POST /api/add-random-words HTTP/1.1" 500 99199
ERROR 2023-03-03 20:43:42,199 log 17168 13768 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:43:42,200 basehttp 17168 13768 "POST /api/add-random-words HTTP/1.1" 500 99199
INFO 2023-03-03 20:44:12,618 autoreload 17168 13180 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:44:13,840 autoreload 13832 13656 Watching for file changes with StatReloader
ERROR 2023-03-03 20:44:25,504 log 13832 2392 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:44:25,506 basehttp 13832 2392 "POST /api/add-random-words HTTP/1.1" 500 99216
ERROR 2023-03-03 20:45:04,732 log 13832 2392 Internal Server Error: /api/add-random-words
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py", line 190, in post
    serializer.save()
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\serializers.py", line 198, in save
    assert not hasattr(self, '_data'), (
AssertionError: You cannot call `.save()` after accessing `serializer.data`.If you need to access data before committing to the database then inspect 'serializer.validated_data' instead. 
ERROR 2023-03-03 20:45:04,733 basehttp 13832 2392 "POST /api/add-random-words HTTP/1.1" 500 99216
INFO 2023-03-03 20:46:41,365 autoreload 13832 13656 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:46:42,606 autoreload 11232 11668 Watching for file changes with StatReloader
INFO 2023-03-03 20:46:46,269 autoreload 11232 11668 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:46:47,643 autoreload 9736 15504 Watching for file changes with StatReloader
INFO 2023-03-03 20:46:51,269 autoreload 9736 15504 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-03 20:46:52,238 autoreload 920 8132 Watching for file changes with StatReloader
INFO 2023-03-03 20:46:58,731 basehttp 920 10304 "POST /api/add-random-words HTTP/1.1" 200 15
INFO 2023-03-06 17:06:27,695 autoreload 12192 11248 Watching for file changes with StatReloader
INFO 2023-03-07 12:07:28,683 autoreload 14432 11212 Watching for file changes with StatReloader
INFO 2023-03-07 19:19:38,964 autoreload 14432 11212 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\tests.py changed, reloading.
INFO 2023-03-07 19:19:41,190 autoreload 16828 7508 Watching for file changes with StatReloader
INFO 2023-03-07 19:19:52,680 autoreload 16828 7508 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\tests.py changed, reloading.
INFO 2023-03-07 19:19:54,090 autoreload 9756 5868 Watching for file changes with StatReloader
INFO 2023-03-07 19:23:38,968 autoreload 9756 5868 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\tests.py changed, reloading.
INFO 2023-03-07 19:23:40,274 autoreload 8208 12840 Watching for file changes with StatReloader
INFO 2023-03-07 19:39:49,496 basehttp 8208 16928 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:39:52,015 basehttp 8208 16928 "POST /api/add-after-search HTTP/1.1" 200 17
INFO 2023-03-07 19:41:05,959 basehttp 8208 16928 "POST /api/add-after-search HTTP/1.1" 200 17
INFO 2023-03-07 19:44:06,906 autoreload 8208 12840 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:44:08,241 autoreload 2256 7560 Watching for file changes with StatReloader
INFO 2023-03-07 19:44:39,393 autoreload 2256 7560 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:44:40,755 autoreload 14304 8784 Watching for file changes with StatReloader
INFO 2023-03-07 19:45:19,517 autoreload 14304 8784 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:45:20,666 autoreload 2768 1968 Watching for file changes with StatReloader
INFO 2023-03-07 19:46:57,163 autoreload 2768 1968 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:46:58,381 autoreload 5164 17800 Watching for file changes with StatReloader
INFO 2023-03-07 19:47:12,590 autoreload 5164 17800 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:47:13,959 autoreload 16124 13428 Watching for file changes with StatReloader
INFO 2023-03-07 19:47:25,732 autoreload 16124 13428 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:47:27,056 autoreload 19904 14916 Watching for file changes with StatReloader
INFO 2023-03-07 19:48:49,502 autoreload 19904 14916 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:48:50,945 autoreload 9340 21268 Watching for file changes with StatReloader
INFO 2023-03-07 19:51:45,445 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:51:53,878 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:51:55,317 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:51:56,653 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:51:57,540 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:51:58,889 basehttp 9340 15560 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:52:23,869 autoreload 9340 21268 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:52:25,312 autoreload 7712 6936 Watching for file changes with StatReloader
INFO 2023-03-07 19:52:31,891 autoreload 7712 6936 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:52:33,048 autoreload 18256 16044 Watching for file changes with StatReloader
INFO 2023-03-07 19:53:41,584 autoreload 18256 16044 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\helpers.py changed, reloading.
INFO 2023-03-07 19:53:43,249 autoreload 12484 2768 Watching for file changes with StatReloader
INFO 2023-03-07 19:53:44,751 basehttp 12484 8256 "POST /api/add-after-search HTTP/1.1" 200 15
INFO 2023-03-07 19:54:29,404 autoreload 12484 2768 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:54:30,755 autoreload 8976 11196 Watching for file changes with StatReloader
INFO 2023-03-07 19:54:32,282 basehttp 8976 13124 "POST /api/add-after-search HTTP/1.1" 200 17
INFO 2023-03-07 19:56:54,779 autoreload 8976 11196 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 19:56:55,865 autoreload 7140 15988 Watching for file changes with StatReloader
INFO 2023-03-07 20:05:21,019 autoreload 7140 15988 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-07 20:05:22,589 autoreload 20584 20836 Watching for file changes with StatReloader
INFO 2023-03-09 13:58:27,018 autoreload 20624 16340 Watching for file changes with StatReloader
INFO 2023-03-09 13:58:34,280 basehttp 20624 11944 "POST /api/add-after-search HTTP/1.1" 200 17
WARNING 2023-03-09 13:58:48,323 log 20624 1992 Not Found: /
WARNING 2023-03-09 13:58:48,323 basehttp 20624 1992 "GET / HTTP/1.1" 404 3485
WARNING 2023-03-09 13:58:48,489 log 20624 1992 Not Found: /favicon.ico
WARNING 2023-03-09 13:58:48,490 basehttp 20624 1992 "GET /favicon.ico HTTP/1.1" 404 3536
INFO 2023-03-09 13:58:53,824 basehttp 20624 1992 "GET /admin/ HTTP/1.1" 200 8493
INFO 2023-03-09 13:58:53,860 basehttp 20624 1992 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,869 basehttp 20624 1992 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,889 basehttp 20624 10520 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,889 basehttp 20624 1992 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,896 basehttp 20624 10520 "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,897 basehttp 20624 1772 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,899 basehttp 20624 13008 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,940 basehttp 20624 13008 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,942 basehttp 20624 1772 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
INFO 2023-03-09 13:58:53,945 basehttp 20624 10520 "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
INFO 2023-03-09 13:58:54,132 basehttp 20624 10520 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-09 13:58:54,132 basehttp 20624 13008 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-09 13:58:54,133 basehttp 20624 1772 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,609 basehttp 20624 10520 "GET /admin/home/rejected/ HTTP/1.1" 200 10521
INFO 2023-03-09 13:58:56,648 basehttp 20624 10520 "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,662 basehttp 20624 1992 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,662 basehttp 20624 13008 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,662 basehttp 20624 1772 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,663 basehttp 20624 14076 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,671 basehttp 20624 1992 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,672 basehttp 20624 14076 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,676 basehttp 20624 1772 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,682 basehttp 20624 19636 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,759 basehttp 20624 19636 "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,791 basehttp 20624 19636 "GET /static/admin/img/search.svg HTTP/1.1" 304 0
INFO 2023-03-09 13:58:56,899 basehttp 20624 10520 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-09 13:58:56,983 basehttp 20624 10520 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
INFO 2023-03-09 13:58:58,743 basehttp 20624 10520 "GET /admin/home/rhymes/ HTTP/1.1" 200 14234
INFO 2023-03-09 13:58:59,237 basehttp 20624 10520 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-09 13:59:06,442 basehttp 20624 10520 "GET /admin/home/rhymes/555/change/ HTTP/1.1" 200 9416
INFO 2023-03-09 13:59:06,552 basehttp 20624 10520 "GET /static/admin/css/forms.css HTTP/1.1" 200 8944
INFO 2023-03-09 13:59:06,554 basehttp 20624 19636 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2023-03-09 13:59:06,597 basehttp 20624 19636 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
INFO 2023-03-09 13:59:06,614 basehttp 20624 19636 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2023-03-09 13:59:06,867 basehttp 20624 1772 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-09 13:59:14,722 basehttp 20624 1772 "GET /admin/home/rhymes/ HTTP/1.1" 200 14234
INFO 2023-03-09 13:59:15,226 basehttp 20624 1772 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
ERROR 2023-03-09 14:00:23,556 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:00:23,559 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80895
ERROR 2023-03-09 14:00:46,413 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:00:46,415 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80895
ERROR 2023-03-09 14:00:51,368 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:00:51,370 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80895
ERROR 2023-03-09 14:00:52,597 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:00:52,598 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80895
ERROR 2023-03-09 14:00:53,073 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:00:53,074 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80895
ERROR 2023-03-09 14:01:59,263 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:01:59,265 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80894
ERROR 2023-03-09 14:02:00,388 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:02:00,390 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80894
ERROR 2023-03-09 14:20:27,813 log 20624 11944 Internal Server Error: /api/home-input
Traceback (most recent call last):
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\venv\lib\site-packages\rest_framework\views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
ERROR 2023-03-09 14:20:27,814 basehttp 20624 11944 "POST /api/home-input HTTP/1.1" 500 80894
INFO 2023-03-09 14:28:32,493 basehttp 20624 4792 "GET /admin/home/rhymes/ HTTP/1.1" 200 14234
INFO 2023-03-09 14:28:32,959 basehttp 20624 4792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
WARNING 2023-03-09 14:28:33,035 log 20624 4792 Not Found: /favicon.ico
WARNING 2023-03-09 14:28:33,036 basehttp 20624 4792 "GET /favicon.ico HTTP/1.1" 404 3536
INFO 2023-03-09 14:28:34,374 basehttp 20624 4792 "GET /admin/home/rhymes/ HTTP/1.1" 200 14234
INFO 2023-03-09 14:28:34,863 basehttp 20624 4792 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-09 14:37:09,290 basehttp 20624 740 "POST /admin/home/rhymes/ HTTP/1.1" 200 7545
INFO 2023-03-09 14:37:09,334 basehttp 20624 740 "GET /static/admin/js/cancel.js HTTP/1.1" 304 0
INFO 2023-03-09 14:37:10,614 basehttp 20624 740 "POST /admin/home/rhymes/ HTTP/1.1" 302 0
INFO 2023-03-09 14:37:11,025 basehttp 20624 740 "GET /admin/home/rhymes/ HTTP/1.1" 200 12180
INFO 2023-03-09 14:37:11,490 basehttp 20624 740 "GET /admin/jsi18n/ HTTP/1.1" 200 3343
INFO 2023-03-09 14:37:11,550 basehttp 20624 740 "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
INFO 2023-03-09 17:53:18,875 autoreload 20624 16340 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-09 17:53:20,800 autoreload 14204 13956 Watching for file changes with StatReloader
INFO 2023-03-09 18:19:55,765 autoreload 14204 13956 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\home\views.py changed, reloading.
INFO 2023-03-09 18:19:57,143 autoreload 16336 6820 Watching for file changes with StatReloader
INFO 2023-03-09 18:20:03,725 autoreload 16336 6820 C:\VE\000_Client\Blake_Dictionary_Working - Copy\backend\accounts\api.py changed, reloading.
INFO 2023-03-09 18:20:05,181 autoreload 21304 724 Watching for file changes with StatReloader
